name: Update Bus Data

# on:
#   schedule:
#     - cron: '0 0 * * *'  # 한국시간 오전 9시 실행

#  이후 데이터 업데이트 필요시 cron 수정
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

# Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests xmltodict
        pip install fastapi uvicorn httpx

    - name: Run update script
      env:
        SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
      run: |
        python busdatasave.py

# Git Push
    - name: Commit and push changes
      run: |
        git config --local user.email "pozuhtuhv@gmail.com"
        git config --local user.name "Hyeonseok-Cho"
        git add -A
        git commit -m "(update) bus and station data"
        git push